name: Deploy to Portainer

on:
  push:
    branches:
      - master  # Déclenche quand tu push sur master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Java et Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compiler le projet avec Maven
        run: mvn clean package -DskipTests

      - name: Unclenched le Webhook Portainer (ignorer SSL)
        run:
          curl -k -X POST -H "Content-Type: application/json" -d '{}' "https://62.72.32.187:9443/api/stacks/webhooks/0394d252-8a19-48d0-8ac3-1b5b070dacdc"

#      - name: Connexion à Docker Hub
#        env:
#          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
#          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
#        run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
#
#
#      - name: Builder et pousser l’image Docker
#        run: |
#          docker build -t josephtie/hyban:latest .
#          docker push josephtie/hyban:latest


